openapi: 3.0.0
info:
  title: API de Usuários e Produtos
  version: 1.0.0
  description: Documentação da API de usuários, administradores e produtos

servers:
  - url: http://localhost:4000/api
    description: Servidor Local

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []

paths:
  /register/admin:
    post:
      summary: Cria um novo administrador
      tags:
        - Admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "admin@email.com"
                password:
                  type: string
                  example: "123456"
      responses:
        201:
          description: Administrador criado com sucesso
        500:
          description: Erro ao registrar administrador

  /register:
    post:
      summary: Cria um novo usuário (Apenas Admin pode criar)
      tags:
        - Usuário
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "user@email.com"
                password:
                  type: string
                  example: "123456"
      responses:
        201:
          description: Usuário criado com sucesso
        403:
          description: Acesso negado
        500:
          description: Erro ao registrar usuário

  /login:
    post:
      summary: Realiza login e retorna um token JWT
      tags:
        - Autenticação
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "user@email.com"
                password:
                  type: string
                  example: "123456"
      responses:
        200:
          description: Login realizado com sucesso
        401:
          description: Credenciais inválidas
        500:
          description: Erro ao realizar login

  /users:
    get:
      summary: Lista todos os usuários cadastrados pelo administrador autenticado
      tags:
        - Usuário
      security:
        - BearerAuth: []
      responses:
        200:
          description: Lista de usuários retornada com sucesso
        403:
          description: Acesso negado
        500:
          description: Erro ao buscar usuários

  /users/{id}:
    delete:
      summary: Deleta um usuário (Apenas Admin)
      tags:
        - Usuário
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID do usuário a ser deletado
      responses:
        200:
          description: Usuário deletado com sucesso
        403:
          description: Acesso negado
        500:
          description: Erro ao deletar usuário

  /users/{id}/password:
    put:
      summary: Atualiza a senha de um usuário (Admin ou o próprio usuário)
      tags:
        - Usuário
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID do usuário a ter a senha alterada
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                newPassword:
                  type: string
                  example: "novaSenha123"
      responses:
        200:
          description: Senha atualizada com sucesso
        403:
          description: Acesso negado
        500:
          description: Erro ao atualizar a senha

  /products:
    post:
      summary: Cadastra um novo produto (Apenas Admin)
      tags:
        - Produtos
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                itemType:
                  type: string
                  example: "Eletrônico"
                supplier:
                  type: string
                  example: "Fornecedor X"
                name:
                  type: string
                  example: "Teclado Mecânico"
                quantity:
                  type: integer
                  example: 10
                unit:
                  type: string
                  example: "unidade"
                expirationDate:
                  type: string
                  format: date
                  example: "2025-12-31"
      responses:
        201:
          description: Produto cadastrado com sucesso
        403:
          description: Acesso negado
        500:
          description: Erro ao cadastrar produto

    get:
      summary: Lista os produtos disponíveis (Admin e Usuários vinculados)
      tags:
        - Produtos
      security:
        - BearerAuth: []
      responses:
        200:
          description: Lista de produtos retornada com sucesso
        403:
          description: Acesso negado
        500:
          description: Erro ao buscar produtos

  /products/{id}:
    delete:
      summary: Deleta um produto (Apenas Admin que cadastrou)
      tags:
        - Produtos
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID do produto a ser deletado
      responses:
        200:
          description: Produto deletado com sucesso
        403:
          description: Acesso negado
        500:
          description: Erro ao deletar produto
